[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_eol = CRLF
monitor_filters = send_on_enter
lib_deps =
    robocore/RoboCore - SMW_SX1276M0
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    sandeepmistry/LoRa @ ^0.8.0
    arduino-libraries/NTPClient @ ^3.2.1